apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: alertmanager-webhook-secret
  namespace: monitoring
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.global.grafanaIdentityClientId | quote }}
    keyvaultName: {{ .Values.keyVaultName | quote }}
    tenantId: {{ .Values.keyVaultTenantId | quote }}
    objects: |
      array:
        - |
          objectName: alertmanager-teams-webhook
          objectType: secret
  secretObjects:
    - secretName: alertmanager-webhook-raw
      type: Opaque
      data:
        - objectName: alertmanager-teams-webhook
          key: webhook-url