apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    clientID: {{ .Values.global.grafanaIdentityClientId | quote }}
    keyvaultName: {{ .Values.keyVaultName | quote }}
    tenantId: {{ .Values.keyVaultTenantId | quote }}
    objects: |
      array:
        - |
          objectName: grafana-admin-password
          objectType: secret
  secretObjects:
    - secretName: grafana-admin-credentials
      type: Opaque
      data:
        - objectName: grafana-admin-password
          key: admin-password