// --- fast window (5m) 
let sloTargetPercent = 99.5;
requests
| where TimeGenerated > ago(5m)
| summarize
    totalRequests = count(),
    failedRequests = countif(success == false)
| extend currentErrorRatePercent = round( 100.0 * failedRequests / totalRequests, 4 )
| extend allowedErrorRatePercent = 100.0 - sloTargetPercent
| extend burnRate = round( currentErrorRatePercent / allowedErrorRatePercent, 2)
| where totalRequests > 0
| project burnRate

// --- slow window (1h) 
let sloTargetPercent = 99.5;
requests
| where TimeGenerated > ago(1h)
| summarize
    totalRequests = count(),
    failedRequests = countif(success == false)
| extend currentErrorRatePercent = round( 100.0 * failedRequests / totalRequests, 4 )
| extend allowedErrorRatePercent = 100.0 - sloTargetPercent
| extend burnRate = round( currentErrorRatePercent / allowedErrorRatePercent, 2)
| where totalRequests > 0
| project burnRate