global:
  grafanaIdentityClientId: "ff0d4c34-555e-4f98-a796-29f54121c8d0" # Grafana's managed identity client ID
keyVaultName: "omotayo-aks-kv"
keyVaultTenantId: "175d86cd-6e18-4ee9-84a6-c6b0d003ecc9"
kube-prometheus-stack:
  grafana:
    serviceAccount:
      create: true
      name: grafana
      annotations:
        azure.workload.identity/client-id: "{{ .Values.global.grafanaIdentityClientId }}" # Grafana's managed identity client ID
    podLabels:
      azure.workload.identity/use: "true"
    admin:
      existingSecret: grafana-admin-credentials
      passwordKey: admin-password
    ingress:
      enabled: false # no domain yet — access via kubectl port-forward until DNS is ready
    service:
      type: ClusterIP
    extraSecretMounts:
      - name: grafana-admin-secret-mount
        mountPath: /mnt/secrets-store
        readOnly: true
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: grafana-admin-secret
    additionalDataSources:
      - name: Azure Monitor
        type: grafana-azure-monitor-datasource
        access: proxy
        jsonData:
          azureAuthType: workloadidentity
          subscriptionId: "81da4d58-2cce-415e-b178-7288e443b4a0" # Azure subscription ID
          tenantId: "175d86cd-6e18-4ee9-84a6-c6b0d003ecc9" # Azure tenant ID
          clientId: "{{ .Values.global.grafanaIdentityClientId }}" # Grafana's managed identity client ID
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        folder: /tmp/dashboards
        searchNamespace: ALL
  prometheus:
    prometheusSpec:
      retention: 15d
      resources:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
  alertmanager:
    alertmanagerSpec:
      alertmanagerConfigSelector:
        matchLabels:
          alertmanagerConfig: default
    config:
      route:
        receiver: 'null'
      receivers:
        - name: 'null'
